name        : perl-extutils-makemaker
version     : 7.10
release     : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.10.tar.gz : 83b76cd49e458a55774e2e8d87bd1107bc159ba4219600c8ef10c6b43b0d94c5
license     :
    - Artistic-Perl-1.0
summary     : ExtUtils::MakeMaker - Create a module Makefile
component   : programming.perl
builddeps   :
    - perl
description : |
    ExtUtils::MakeMaker - Create a module Makefile
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/share/man/man1
