name       : perl-extutils-makemaker
version    : '7.34'
release    : 12
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.34.tar.gz : 95f1eb44de480d00b28d031b574ec868f7aeeee199eb5abe5666f6bcbbf68480
license    : Artistic-Perl-1.0
summary    : ExtUtils::MakeMaker - Create a module Makefile
component  : programming.perl
description: |
    ExtUtils::MakeMaker - Create a module Makefile
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/share/man/man1
check      : |
    %perl_build test
