name       : perl-extutils-makemaker
version    : '7.24'
release    : 8
source     :
    - http://search.cpan.org/CPAN/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.24.tar.gz : 416abc97c3bb2cc72bef28852522f2859de53e37bf3d0ae8b292067d78755e69
license    : Artistic-Perl-1.0
summary    : ExtUtils::MakeMaker - Create a module Makefile
component  : programming.perl
builddeps  :
    - perl
description: |
    ExtUtils::MakeMaker - Create a module Makefile
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/share/man/man1
