name       : perl-extutils-makemaker
version    : '7.32'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.32.tar.gz : 9a269f52ab59b125eb80b968271d9f49da0975d43e51363dbfd1695000ed69de
license    : Artistic-Perl-1.0
summary    : ExtUtils::MakeMaker - Create a module Makefile
component  : programming.perl
description: |
    ExtUtils::MakeMaker - Create a module Makefile
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/share/man/man1
check      : |
    %perl_build test
