name       : perl-extutils-makemaker
version    : '7.30'
release    : 9
source     :
    - http://search.cpan.org/CPAN/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.30.tar.gz : e081a8aa61c56565746bee998bf4c32926c030b84bb3f206e81714a1707f393c
license    : Artistic-Perl-1.0
summary    : ExtUtils::MakeMaker - Create a module Makefile
component  : programming.perl
description: |
    ExtUtils::MakeMaker - Create a module Makefile
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/share/man/man1
check      : |
    %perl_build test
