name       : perl-extutils-makemaker
version    : '7.64'
release    : 16
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.64.tar.gz : 4a6ac575815c0413b1f58967043cc9f2e166446b73c687f9bc62b5eaed9464a0
homepage   : https://metacpan.org/pod/ExtUtils::MakeMaker
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : ExtUtils::MakeMaker - Create a module Makefile
description: |
    This utility is designed to write a Makefile for an extension module from a Makefile.PL. It is based on the Makefile.SH model provided by Andy Dougherty and the perl5-porters.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
    rm -rf $installdir/usr/bin
    rm -rf $installdir/usr/share/man/man1
check      : |
    %perl_build test
